export const API_BASE_URL_GOOGLE = "https://www.googleapis.com/books/v1/volumes?q={my-search}"
export const API_BASE_URL_OPEN_API = "https://openlibrary.org/search.json?q={my-search}"
export const DEFAULT_IMAGE= "https://picsum.photos/200/260"
export const CLEAR_LIST_COMMENTS = "Limpiar Lista de comentarios"
export const ADD_TO_FAVORITE = "Agregar a Favoritos"
export const DELETE_TO_FAVORITE = "Quitar de Favoritos"
